#ifndef PLATFORMGLOBAL_H
#define PLATFORMGLOBAL_H

#include <QObject>

#if defined(PLATFORMMANAGER_GLOBAL)
#define PLATFORMSHARED_EXPORT Q_DECL_EXPORT
#else
#define PLATFORMSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif  // PLATFORMGLOBAL_H
